source.. = src/,\
           resources/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               css/default.css,\
               Application.e4xmi,\
               OSGI-INF/,\
               resources/

